"""empty message

Revision ID: 15efe0b969dd
Revises: 4a2af9d67737
Create Date: 2020-05-04 18:00:38.866884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15efe0b969dd'
down_revision = '4a2af9d67737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ower', sa.Integer(), nullable=False),
    sa.Column('payer', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_settled', sa.Enum('Y', 'N'), server_default='N', nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.Column('modified_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ower'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement')
    op.drop_table('events')
    # ### end Alembic commands ###
