"""empty message

Revision ID: 3f1bc1b6aa12
Revises: 
Create Date: 2020-05-04 21:28:24.627194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1bc1b6aa12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.Column('modified_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Enum('Y', 'N'), server_default='N', nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.Column('modified_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ower', sa.Integer(), nullable=False),
    sa.Column('payer', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_settled', sa.Enum('Y', 'N'), server_default='N', nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.Column('modified_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ower'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payer', sa.Integer(), nullable=False),
    sa.Column('ower', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Enum('Y', 'N'), server_default='Y', nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.Column('modified_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event'], ['eventlog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group'], ['friend_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ower'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('access', sa.Enum('moderator', 'participant'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.Column('modified_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['friend_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group')
    op.drop_table('transactions')
    op.drop_table('settlement')
    op.drop_table('friend_groups')
    op.drop_table('events')
    op.drop_table('user')
    op.drop_table('eventlog')
    # ### end Alembic commands ###
