"""empty message

Revision ID: 4a2af9d67737
Revises: e357a6290286
Create Date: 2020-05-04 17:55:00.845012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a2af9d67737'
down_revision = 'e357a6290286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('ower', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('payer', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('reason', sa.String(length=64), nullable=False))
    op.drop_constraint('transactions_ibfk_1', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_ibfk_2', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'user', ['ower'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'user', ['payer'], ['id'], ondelete='CASCADE')
    op.drop_column('transactions', 'receiver')
    op.drop_column('transactions', 'done')
    op.drop_column('transactions', 'sender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('done', mysql.ENUM('Y', 'N'), nullable=True))
    op.add_column('transactions', sa.Column('receiver', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_ibfk_2', 'transactions', 'user', ['sender'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('transactions_ibfk_1', 'transactions', 'user', ['receiver'], ['id'], ondelete='CASCADE')
    op.drop_column('transactions', 'reason')
    op.drop_column('transactions', 'payer')
    op.drop_column('transactions', 'ower')
    # ### end Alembic commands ###
