"""empty message

Revision ID: 7887288a8ce5
Revises: 15efe0b969dd
Create Date: 2020-05-04 18:05:13.725062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7887288a8ce5'
down_revision = '15efe0b969dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settlement', 'is_settled',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=False,
               existing_server_default=sa.text("'N'"))
    op.alter_column('transactions', 'group',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'valid',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=False,
               existing_server_default=sa.text("'Y'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'valid',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=True,
               existing_server_default=sa.text("'Y'"))
    op.alter_column('transactions', 'group',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('settlement', 'is_settled',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=True,
               existing_server_default=sa.text("'N'"))
    # ### end Alembic commands ###
