"""empty message

Revision ID: b198891186ef
Revises: ea52a0c59921
Create Date: 2020-05-02 18:52:19.267207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b198891186ef'
down_revision = 'ea52a0c59921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('group', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('valid', sa.Enum('Y', 'N'), server_default='Y', nullable=True))
    op.create_foreign_key(None, 'transactions', 'friend_groups', ['group'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'valid')
    op.drop_column('transactions', 'group')
    # ### end Alembic commands ###
