"""empty message

Revision ID: e357a6290286
Revises: e974ba868b5b
Create Date: 2020-05-03 01:05:10.882155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e357a6290286'
down_revision = 'e974ba868b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_groups', sa.Column('creator', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'friend_groups', 'user', ['creator'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friend_groups', type_='foreignkey')
    op.drop_column('friend_groups', 'creator')
    # ### end Alembic commands ###
