"""empty message

Revision ID: e974ba868b5b
Revises: b198891186ef
Create Date: 2020-05-02 18:54:02.024619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e974ba868b5b'
down_revision = 'b198891186ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_groups', sa.Column('deleted', sa.Enum('Y', 'N'), server_default='N', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friend_groups', 'deleted')
    # ### end Alembic commands ###
